spring.application.name: gateway
spring.profiles.active: local

spring:
  config:
    import:
      - monitoring.yml
      - logging.yml
  web.resources.add-mappings: false
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-api
          uri: lb://auth-api
          predicates:
            - Path=/auth/**
        - id: order-api
          uri: lb://order-api
          predicates:
            - Path=/api/v1/order/**
        - id: product-api
          uri: lb://product-api
          predicates:
            - Path=/api/v1/product/**
      discovery:
        locator:
          enabled: true

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
  port: 19091


---
spring.config.activate.on-profile: local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

---
spring.config.activate.on-profile: local-dev


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: prod


